# Generated by Django 3.2.4 on 2021-07-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='account_activated',
            field=models.BooleanField(default=False),
        ),
    ]
