# Generated by Django 3.2.4 on 2021-11-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210713_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
