# Generated by Django 3.2.4 on 2021-10-01 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Categorie',
        ),
    ]
