# Generated by Django 3.2.4 on 2021-10-07 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_categories_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.categorie'),
        ),
    ]
