# Generated by Django 3.2.4 on 2021-10-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_item_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.CharField(blank=True, choices=[('S', 'sale'), ('N', 'new'), ('L', 'limited')], max_length=1, null=True),
        ),
    ]
