# Generated by Django 3.2.4 on 2021-10-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_item_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='images',
            new_name='main_image',
        ),
    ]
