# Generated by Django 3.2.4 on 2021-10-23 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.categorie'),
        ),
    ]
