# Generated by Django 3.2.4 on 2021-10-23 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_image_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categorie',
            field=models.ForeignKey(default='Diversos', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.categorie'),
        ),
    ]
