# Generated by Django 3.2.4 on 2021-10-23 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_item_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='categorie',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='categorie',
            field=models.ForeignKey(default='Diversos', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.categorie', to_field='categorie'),
        ),
    ]
