# Generated by Django 3.2.4 on 2021-10-30 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='content',
        ),
    ]
