# Generated by Django 3.2.4 on 2021-11-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20211102_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
