# Generated by Django 3.2.4 on 2021-11-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_alter_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='old_discount',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='old_shipping',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True),
        ),
    ]
