# Generated by Django 3.2.4 on 2021-11-26 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_auto_20211126_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='old_discount',
        ),
    ]
