# Generated by Django 3.2.4 on 2021-12-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_alter_item_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
