# Generated by Django 3.2.4 on 2021-12-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_alter_item_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
    ]
