# Generated by Django 3.2.4 on 2021-12-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_alter_item_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='old_shipping',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
    ]
