# Generated by Django 3.2.4 on 2021-12-11 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_order_old_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='shipping',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='old_shipping',
        ),
    ]
