# Generated by Django 3.2.4 on 2021-12-15 09:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_auto_20211211_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 12, 15, 9, 49, 6, 317252, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
