# Generated by Django 3.2.4 on 2021-12-16 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
