# Generated by Django 3.2.4 on 2021-12-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0058_auto_20211216_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='email',
            field=models.EmailField(blank=True, max_length=70, verbose_name='email'),
        ),
    ]
