# Generated by Django 3.2.4 on 2022-01-17 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0062_orderitem_replica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
