# Generated by Django 3.2.4 on 2022-01-17 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0063_auto_20220117_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='RefundedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.orderitem')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.refund')),
            ],
        ),
    ]
